version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    command: bash -c "make sam db:migrate ; crystal run ./src/api.cr"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_travels
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - db